### ISSUE TITLE
Status data object not available in vertx-health-checks-js/health_check_handler

### ISSUE THREAD

**Issue by chefhoobajoob** [vert-x3/vertx-health-check#8]
It seems that the javascript shims to not provide a way to get hold of a Status object for completing futures in health check handlers.

@cescoffier : Is there a working example of a health check handler in Javascript completing the handler's future using the Status.OK/KO methods?

**Comment by chefhoobajoob** [comment]
We found our own codegen workaround for producing status objects in Javascript, but please advise if there's a way to do this with the as-is javascript shims.

```java
@VertxGen
public interface StatusFactory {
    static Status ok() { return Status.OK(); }
    static Status ok( JsonObject data ) { return Status.OK( data ); }

    static Status ko() { return Status.KO(); }
    static Status ko( JsonObject data ) { return Status.KO( data ); }
}
```

**Comment by chefhoobajoob** [comment]
Actually, this seems only to be a small problem. We are finding that the javascript bindings for this library cannot call the handler's Future.complete/fail methods with any arguments.

If we do call complete/fail with a status object, we are getting the exception below. I'll try to get a reproducer together.

```
2017-06-08T13:27:18,395-0700 [vert.x-eventloop-thread-5] ERROR i.v.e.w.impl.RoutingContextImplBase - Unexpected exception in route
java.lang.IllegalStateException: Result is already complete: succeeded
    at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:121) ~[vertx-core-3.4.1.jar:na]
    at io.vertx.ext.healthchecks.impl.DefaultProcedure.check(DefaultProcedure.java:55) ~[vertx-health-check-3.4.1.jar:na]
    at io.vertx.ext.healthchecks.impl.DefaultCompositeProcedure.check(DefaultCompositeProcedure.java:60) ~[vertx-health-check-3.4.1.jar:na]
    at io.vertx.ext.healthchecks.impl.HealthChecksImpl.compute(HealthChecksImpl.java:135) ~[vertx-health-check-3.4.1.jar:na]
    at io.vertx.ext.healthchecks.impl.HealthChecksImpl.invoke(HealthChecksImpl.java:80) ~[vertx-health-check-3.4.1.jar:na]
    at io.vertx.ext.healthchecks.impl.HealthChecksImpl.invoke(HealthChecksImpl.java:87) ~[vertx-health-check-3.4.1.jar:na]
    at io.vertx.ext.healthchecks.impl.HealthCheckHandlerImpl.handle(HealthCheckHandlerImpl.java:71) ~[vertx-health-check-3.4.1.jar:na]
    at jdk.nashorn.internal.scripts.Script$Recompilation$2166$2113A$\^eval\_#88\!17\^eval\_.L:1$HealthCheckHandler$handle(vertx-health-checks-js/health_check_handler.js:57) ~[na:na]
    at jdk.nashorn.internal.scripts.Script$Recompilation$391$5522A$\^eval\_#88\!17\^eval\_.L:1$Route$handler$L:156(vertx-web-js/route.js:157) [na:na]
    at io.vertx.core.Handler$$NashornJavaAdapter.handle(Unknown Source) [na:na]
    at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) [vertx-web-3.4.1.jar:na]
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) [vertx-web-3.4.1.jar:na]
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118) [vertx-web-3.4.1.jar:na]
    at jdk.nashorn.internal.scripts.Script$Recompilation$2164$3086$\^eval\_#88\!17\^eval\_.L:1$RoutingContext$next(vertx-web-js/routing_context.js:93) [na:na]
    at jdk.nashorn.internal.scripts.Script$Recompilation$2154$8953A$\^eval\_#88\!17\^eval\_.L:1$vertxStartAsync$L:187$L:212(rest-verticle/main.js:214) [na:na]
    at jdk.nashorn.internal.scripts.Script$Recompilation$391$5522A$\^eval\_#88\!17\^eval\_.L:1$Route$handler$L:156(vertx-web-js/route.js:157) [na:na]
    at io.vertx.core.Handler$$NashornJavaAdapter.handle(Unknown Source) [na:na]
    at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) [vertx-web-3.4.1.jar:na]
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) [vertx-web-3.4.1.jar:na]
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118) [vertx-web-3.4.1.jar:na]
    at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:121) [vertx-web-3.4.1.jar:na]
    at jdk.nashorn.internal.scripts.Script$Recompilation$2153$1256A$\^eval\_#88\!17\^eval\_.L:1$CorsHandler$handle(vertx-web-js/cors_handler.js:43) [na:na]
    at jdk.nashorn.internal.scripts.Script$Recompilation$391$5522A$\^eval\_#88\!17\^eval\_.L:1$Route$handler$L:156(vertx-web-js/route.js:157) [na:na]
    at io.vertx.core.Handler$$NashornJavaAdapter.handle(Unknown Source) [na:na]
    at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) [vertx-web-3.4.1.jar:na]
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) [vertx-web-3.4.1.jar:na]
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118) [vertx-web-3.4.1.jar:na]
    at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:202) [vertx-web-3.4.1.jar:na]
    at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:180) [vertx-web-3.4.1.jar:na]
    at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:67) [vertx-web-3.4.1.jar:na]
    at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:406) ~[vertx-core-3.4.1.jar:na]
    at io.vertx.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:297) ~[vertx-core-3.4.1.jar:na]
    at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:441) ~[vertx-core-3.4.1.jar:na]
    at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131) ~[vertx-core-3.4.1.jar:na]
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:666) ~[vertx-core-3.4.1.jar:na]
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:573) ~[vertx-core-3.4.1.jar:na]
    at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71) ~[vertx-core-3.4.1.jar:na]
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335) ~[vertx-core-3.4.1.jar:na]
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193) ~[vertx-core-3.4.1.jar:na]
    at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:71) ~[vertx-core-3.4.1.jar:na]
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122) ~[vertx-core-3.4.1.jar:na]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1228) ~[netty-handler-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039) ~[netty-handler-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.8.Final.jar:4.1.8.Final]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
 ```

**Comment by chefhoobajoob** [comment]
I guess the workaround in the absence of js-accessible factory functions is to just pass in a json object that includes the same fields produced by `Status.OK()`?

So, complete using:
```javascript
future.complete({ok: false, data: {someData: 14}})
```

I think this would work, but we are currently runing into the bug described in issue #9 when trying to complete the future with status.
